### ISSUE TITLE
Divisão de tarefas!

### ISSUE THREAD

**Issue by bruno5198** [bruno5198/Trabalho3-Grupo1#1]
Boa tarde malta,

Visto que já temos o guião relativo ao trabalho prático, sugiro que comecemos já a dividir tarefas no sentido de começar a trabalhar o quanto antes. Como preferem fazer?
@MartinRivadeneira @IvoBastos 

P.s.: Não marco o André porque ele ainda não aceitou o convite...

**Comment by IvoBastos** [comment]
Boas, 
Eu não faço questão de ficar com nenhuma parte específica. Porém, tal como disse, ainda não vi as aulas e não sei ao certo como  é que se poderá dividir o trabalho. Se quiserem decidir isso vocês por mim tudo bem e depois faço a parte que me compete. Senão, podemos reunir no fim de semana, ou para a semana e vemos isso. Como quiserem!

**Comment by bruno5198** [comment]
Eu estou de acordo em fazer uma reunião este fim de semana (ou no próximo...).

**Comment by bruno5198** [comment]
Apenas para que fique registado, a divisão de tarefas definida (na reunião da passada sexta feira) foi:

- O @MartinRivadeneira desenvolverá um código que permita controlar os robôs de uma determinada equipa (da equipa Vermelha, por exemplo);

- O @bruno5198 desenvolverá o código que permite controlar os robôs de outra das equipas (da equipa Verde, por exemplo);

- O @IvoBastos e o @andredvasconcelos desenvolverão, em conjunto, o código que permitirá controlar os robôs da terceira equipa (a equipa Azul, por exemplo);

Desta forma, ainda que os códigos desenvolvidos venham a ser semelhantes, na medida em que todos temos acesso e partilhamos ideias relativamente ao que vamos desenvolver, poderemos fazer uma competição amigável dentro do grupo, vendo quem consegue uma melhor pontuação.
