### ISSUE TITLE
Manual driving race - Teleop (Conclusão)!

### ISSUE THREAD

**Issue by bruno5198** [bruno5198/Trabalho3-Grupo1#10]
Boas malta!

@andredvasconcelos Como está aquela questão de conseguir ver a imagem proveniente da câmera no telemóvel? Conseguiste colocar isso a funcionar?
De qualquer forma, penso que seria interessante se gravasses um video (com umas montagens engraçadas para que se veja quer a pista quer o telemóvel a partir do qual se está a controlar o robô) para que o possamos colocar aqui, no github. Tratas disso?

P.s.: Na minha opinião, o vídeo só é válido se conseguires percorrer a pista em menos de 5 segundos! hehehe

**Comment by andredvasconcelos** [comment]
Opa não consegui reseolver isso ate ao momento.
Relativamente a essa tua ideia, parece me uma excelente sugestão.  vou tratar disso!

**Comment by bruno5198** [comment]
Ok. Vou deixar este issue aberto para que possas ir dando o feedback de como está a correr...

**Comment by MartinRivadeneira** [comment]
De facto, não sei se viram o mail do professor, mas ele quer no youtube dois videos, um com a condução manual sobre a pista e um com o jogo teamhunt.... @andredvasconcelos consegues tratar do video da condução manual?

**Comment by bruno5198** [comment]
@andredvasconcelos Como estamos relativamente à questão do vídeo demonstrativo da componente de condução manual de um robô?

**Comment by andredvasconcelos** [comment]
vou fazer agora de tarde

**Comment by bruno5198** [comment]
Conclui-se a componente de conduão manual com os dois vídeos que se seguem:
- Condução com o recurso ao controlador do ROS: [![Condução Manual - Controlador ROS](https://github.com/bruno5198/Trabalho3-Grupo1/blob/main/Trabalho3-Grupo1/docs/Manual%20driving%20with%20ROS%20controller.png)](https://www.youtube.com/watch?v=mcEqHTWQLvI)
- Condução com o recurso à aplicação ROS Control: [![Condução Manual - ROS Control application](https://github.com/bruno5198/Trabalho3-Grupo1/blob/main/Trabalho3-Grupo1/docs/Manual%20driving%20with%20ROS%20Control%20application.png)](https://www.youtube.com/watch?v=NBYDDc-LTdQ)
