### ISSUE TITLE
Pacotes th_description & th_referee

### ISSUE THREAD

**Issue by bruno5198** [bruno5198/Trabalho3-Grupo1#11]
Bos malta!

@MartinRivadeneira É impressão minha ou na tua versão do trabalho ([p_mrivadeneira](https://github.com/bruno5198/Trabalho3-Grupo1/tree/main/p_mrivadeneira)) não tens os pacotes que contém as arenas e o árbitro?

**Comment by MartinRivadeneira** [comment]
Boas malta!

@bruno5198 por acaso não os tenho. Mas é melhor, pois não convem termos os dois visto que uma pessoa que clona o codigo teria problemas em compilar por ter pacotes com os mesmos nomes. Mas convinha depois colocarmos esses pacotes numa pasta separada. Depois tratamos disso!

**Comment by bruno5198** [comment]
Sim, faz sentido.

Vou deixar este issue aberto como lembrete para **colocarmos esses pacotes numa pasta separada**.

**Comment by bruno5198** [comment]
Penso que esta questão está tratada, estando os pacotes em causa [aqui](https://github.com/bruno5198/Trabalho3-Grupo1/tree/main/Trabalho3-Grupo1/TeamHunt).
