### ISSUE TITLE
Adição de uma junta rotacional ao robô.

### ISSUE THREAD

**Issue by bruno5198** [bruno5198/Trabalho3-Grupo1#2]
Bom dia malta,

Estou com alguns problemas em conseguir alterar a geometria do robô...

Caso adicione ao robô uma junta fixa, não tenho qualquer problema, no entanto, quando tento adicionar uma junta rotacional ela nem sequer aparece....Já experimentei fazer uma junta semelhante à das rodas (do tipo continua) mas também não resultou....Algum de vocês (@MartinRivadeneira, @IvoBastos, @andredvasconcelos ) sabe como resolver este problema?

**Comment by MartinRivadeneira** [comment]
Bom dia @bruno5198,

Não sei se te lembras, mas na reunião também mostrei-te que tinha acrescentado braços aos robôs, com o fim de conseguir movimentá-los quando estiver perto de um target. No entanto, também não consegui fazer nem do type "continuos" nem do type "revolute"... simplesmente da erro, e até agora só consegui fazer juntas do type "fixed".

Se calhar era uma boa ideia fazer um issue no repositório de psr a perguntar aquilo ao prof.... não se se tem a ver com o facto de ser um xacro e quando nós fizemos isso era para um urdf só.... não tenho certeza...

**Comment by andredvasconcelos** [comment]
> Bom dia malta,
> 
> Estou com alguns problemas em conseguir alterar a geometria do robô...
> 
> Caso adicione ao robô uma junta fixa, não tenho qualquer problema, no entanto, quando tento adicionar uma junta rotacional ela nem sequer aparece....Já experimentei fazer uma junta semelhante à das rodas (do tipo continua) mas também não resultou....Algum de vocês (@MartinRivadeneira, @IvoBastos, @andredvasconcelos ) sabe como resolver este problema?

Boas pessoal,

Muito honestamente não faço ideia como resolver tal situação

**Comment by bruno5198** [comment]
Obrigado malta.
