### ISSUE TITLE
Manual driving race - Teleop!

### ISSUE THREAD

**Issue by bruno5198** [bruno5198/Trabalho3-Grupo1#3]
Bom dia malta,

Não sei se já tiveram oportunidade de ver, mas o professor ja colocou no elearning os critérios de avaliação para este trabalho, onde se pode ver que será dado um peso de 10% à condução manual do robô...
Neste sentido, penso que seria importante "gastar" algum tempo a tentar controlar o robô, por exemplo, através de um joystick. Algum de vocês tem algum?

Como eu não tenho nenhum joystick e o @MartinRivadeneira está mais dedicado à parte do jogo "Team hunt", penso que poderia ficar um de vocês (@IvoBastos ou @andredvasconcelos) com este desafio. Concordam?

Coloco aqui alguns links que talvês possam ser úteis:
- http://wiki.ros.org/ps3joy/Tutorials/PairingJoystickAndBluetoothDongle
- http://wiki.ros.org/ps3joy/Tutorials/WritingTeleopNode
- https://emanual.robotis.com/docs/en/platform/turtlebot3/basic_operation/

**Comment by IvoBastos** [comment]
Boas, eu posso tentar ver o que consigo fazer. Mas não tenho nenhum joystick infelizmente

**Comment by MartinRivadeneira** [comment]
@andredvasconcelos Por acaso tu não tens um jostick ou comando de PlayStation?

**Comment by bruno5198** [comment]
@andredvasconcelos Tens algum joystick/comando de PlayStation/comando de XBOX/etc...? Consegues tratar desta questão da condução em modo manual?

**Comment by andredvasconcelos** [comment]
> @andredvasconcelos Tens algum joystick/comando de PlayStation/comando de XBOX/etc...? Consegues tratar desta questão da condução em modo manual?

Opa so tenho mm comanda da ps4 mas nao sei se funciona…. Mas sim eu posso tentar fazer essa parte.

relativamente a parte da condução manual, ja nao estava feita?

**Comment by bruno5198** [comment]
Sim, estava, mas para conduzir com o teclado.....a ideia é fazer algo mais engraçado, como conduzir com o comando de PS4, ou outra coisa qualquer caso alguém tenha alguma ideia engraçada...

Vou então fechar este issue e assumir que ficas encarregue dessa parte....Caso o comando que tens não funcione, avisa...
