### ISSUE TITLE
Mapeamento do cenário (Pacote gmapping)

### ISSUE THREAD

**Issue by bruno5198** [bruno5198/Trabalho3-Grupo1#4]
Boa tarde malta,

@MartinRivadeneira reparei que tens um launch file com as configurações necessárias para um pacote gmapping (link do launch file em questão: https://github.com/bruno5198/Trabalho3-Grupo1/blob/260a07afa468ac3b73cd5d30fa9a469bcd707c73/p_mrivadeneira/p_mrivadeneira_bringup/launch/gmapping.launch), no entanto parece-me que não estás a usa-lo, estou certo?

Coloco esta questão porque também implementei esse mesmo pacote, o pacote gmapping, e consigo obter um mapa do cenário à medida que o robô se vai movimentando, no entanto não sei me sabes dizer se é possível obter a localização dos objetos que vão sendo mapeados?

**Comment by MartinRivadeneira** [comment]
Boas @bruno5198! Pois, a verdade é que não te sei responder. Ainda é preciso perceber para que será necessário o mapeamento no trabalho. Se o objetivo é só imprimir um mapa do cenário no fim, estive a ver na net e acho que não é muito complicado, mas não tentei ainda. Por outro lado, se o objetivo é utilizar o mapeamento no jogo... seria muito mais dificil e ainda não sei bem se vale a pena. A questão é que se calhar podes mandar aos robôs mapear, e comparando os mapas entre eles, quando forem muito parecidos, eles poderiam saber a sua localização em relação a um referencial qualquer definido e poderiam mandar as suas posições ou as posições do target em relação a aquele referencial. Anyway, aquilo parece ser muito complicado de se fazer, para além de que deveriam ser estudados o tipo de mensagens produzidas pelo nó gmapping. Vi um bocado sobre isso e sei que ele manda um tipo de array onde -1 representa incerteza, enquanto que os valores entre 0 e 100 representam certeza de ocupação. Não sei bem como traduzir isto para a utilidade desejada, ou se o objetivo é só meter o gmapping a funcionar, pois o outro problema é que se um robô for apanhado, ele desaparece e aparece na zona quadrada, e isto pode produzir o mapa totalmente errado, pois o mapeamento é feito com odometria e isto altera a posição final do robô, sendo que este poderia não perceber bem a sua nova localização. 

Acho que o melhor seria perguntar ao prof. qual o objetivo do mapeamento...

**Comment by bruno5198** [comment]
Ok...
Achas melhor colocar um issue o repositório de PSR, ou esperamos por uma reunião com o professor (que suponho que irá acontecer...)?

**Comment by MartinRivadeneira** [comment]
Acho que o melhor é esperar. Podemos ir fazenso as outras coisas.... Se depois o prof não dizer nada sobre as reuniões, então nós mandamos mensagem ou assim! (:

**Comment by bruno5198** [comment]
Sim, parece-me bem.

Obrigado!
