### ISSUE TITLE
Alteração do mundo 

### ISSUE THREAD

**Issue by IvoBastos** [bruno5198/Trabalho3-Grupo1#5]
Bom dia malta, estou com alguns problemas ao alterar o mundo no gazebo, por exemplo, para colocar aquela estrada na qual se fez aquela competição, temos de ir buscar o mapa à package disponibilizada no github. Existe alguma forma de fazer o download automático da package toda para o pc? Ou é preciso criar manualmente a package no pc? Não sei se me expliquei bem. Se alguem conseguir ajudar, agradecia

**Comment by bruno5198** [comment]
Bom dia,

Para fazeres o download das coisas que o professor coloca no github tens que copiar o link do repositório referente à UC de PSR, como mostra a imagem e, de seguida, abrir um terminal, ir para a diretoria onde queres que a pasta com o conteúdo do repositório seja criada e correr o comando: git clone "link"

P.s.: Isso irá copiar todo o conteúdo do repositório, o que te pode trazer problemas derivado dos nomes dados pelo professor aos pacotes poderem coincidir com os nomes dados por ti a outros pacotes....

![Sem Título](https://user-images.githubusercontent.com/58600049/152985696-af8eb8cb-d3f9-4de8-aaea-0e6c2243234f.png)

Respondi à tua questão?

**Comment by IvoBastos** [comment]
Obrigado. Então, neste caso, para copiar ao package psr_fnr não consigo fazer o clone só dessa package certo? Tinha de ser o repositório todo?

**Comment by bruno5198** [comment]
Exatamente.

**Comment by IvoBastos** [comment]
![Screenshot from 2022-02-08 18-14-35](https://user-images.githubusercontent.com/92791850/153050493-3c872bfc-b024-4d22-94dc-b5f19f0f2ccf.png)
Obrigado, já consegui
