### ISSUE TITLE
Aplicações GMAPPING

### ISSUE THREAD

**Issue by MartinRivadeneira** [bruno5198/Trabalho3-Grupo1#6]
Boa noite malta,

Vou deixar aqui uns links sobre informação que poderia dar jeito no futuro para a aplicação do gammping.

https://www.nickbenoit.me/turtlebot
https://answers.ros.org/question/287706/simultaneous-autonomous-navigation-and-mapping/
http://wiki.ros.org/frontier_exploration
http://wiki.ros.org/rtabmap_ros/Tutorials/MappingAndNavigationOnTurtlebot#Autonomous_Navigation

**Comment by bruno5198** [comment]
Boa malta!

@MartinRivadeneira O professor inda não colocou a gravação da aula de esclarecimento de dúvidas de ontem online, pois não?
Coloco esta pergunta neste issue pois penso que a aula de ontem permite fechar este issue, na medida em que o professor ajudou a fazer a parte da navegação.

**Comment by MartinRivadeneira** [comment]
Boas @bruno5198. Já mandei um mail ao prof. para ver se ele coloca o video entretanto. Assim que o fizer penso que podes fechar este issue! (:

**Comment by bruno5198** [comment]
Fecho este issue uma vez que já se encontra online o [vídeo](https://www.youtube.com/watch?v=WWUOUchK3Q4&list=PLQN09mzV5mbLK9OvKQf1ZfXpPlBi461zp&index=41&t=6936s) referente à aula de esclarecimento de dúvidas dada pelo professor onde é abordada esta questão da navegação.
