### ISSUE TITLE
Configs Rviz

### ISSUE THREAD

**Issue by IvoBastos** [bruno5198/Trabalho3-Grupo1#7]
Boa tarde pessoal, estava a explorar um pouco mais a questão das configs do rviz para cada um dos players. Criei 3 configs, uma para cada um dos players (red, green1,blue1) e coloquei-as no launch file do visualize, que é chamado pelo bringup. Eu consigo abrir as configs quando faço o launch do bringup, mas como era de esperar as configs abrem todas em simultâneo, mesmo eu tendo apenas dado spawn de um robô. Alguém sabe como posso fazer para lançar apenas a config do rviz, p.e do robô green, somente quando spawnei previamente o green?
![Uploading Screenshot from 2022-02-10 17-54-58.png…]()
![Screenshot from 2022-02-10 17-55-15](https://user-images.githubusercontent.com/92791850/153468394-6c11e8c1-3517-4c46-a05b-dbae2268d682.png)

**Comment by IvoBastos** [comment]
![Screenshot from 2022-02-10 17-54-58](https://user-images.githubusercontent.com/92791850/153468531-01d620c2-b3a7-41fd-ba32-abe916645f97.png)

**Comment by IvoBastos** [comment]
P.s Já tentei fazer um group if, mas não sei bem como fazer e o que tentei não funcionou!

**Comment by bruno5198** [comment]
Boa noite Ivo,

Se bem percebi, quer faças o spawn de um, dois ou três robôs, são sempre lançadas três janelas rviz, correto?

Para que isso não aconteça tens que fazer algo semelhante ao que fiz nos ficheiros bringup.lauch e visualize.launch. Isto é, no ficheiro bringup.launch chamei o ficheiro visualize.launch, com um argumento associado, nomeadamente o nome do robô (_**player_name**_) (linhas 28 a 34 do ficheiro bringup.launch).
Por sua vez, no ficheiro visualize.launch lanço o rviz apenas para o/os robôs "que spawnei", recorrendo para isso ao argumento _**player_name**_.

Ajudei? Ou confundi ainda mais?

**Comment by IvoBastos** [comment]
Eu acho que percebi, obrigado! Vou dar uma vista de olhos no que fizeste
