### ISSUE TITLE
Teleop usando um comando ps3

### ISSUE THREAD

**Issue by IvoBastos** [bruno5198/Trabalho3-Grupo1#8]
Olá pessoal, estive a tentar controlar o robo manualmente usando um comando ps3, e pelo que vi é algo relativamente simples de fazer, no entanto, é necessário instalar alguns pacotes para o efeito. Quando tento instala-los, recebo mensagens de erro a dizer que esse pacote depende de outros. Ao tentar instalar esses outros pacotes recebo outra mensagem de erro a dizer que o pacote não está disponív
![Screenshot from 2022-02-14 12-22-56](https://user-images.githubusercontent.com/92791850/153864218-175a651f-fa33-4a9f-8358-2745972ef6c1.png)
el. Alguém 
![Screenshot from 2022-02-14 12-21-53](https://user-im
![Screenshot from 2022-02-14 12-22-25](https://user-images.githubusercontent.com/92791850/153864203-3debceb0-cd9f-4f90-a98d-9d37bdd4c994.png)
ages.githubusercontent.com/92791850/153864174-fecba8a8-22d2-4b9a-9b9d-5bcc3eb14cbe.png)
sabe como se pode ultrapassar esta questão?

**Comment by andredvasconcelos** [comment]
Boas pessoal,
Penso que seria bastante interessante, na vez de utilizar o comando ps3, utilizar o ros mobile para controlar o robo atraves do telemovel.

O que acham=?

**Comment by bruno5198** [comment]
Parece-me  uma excelente ideia @andredvasconcelos, mas não é "uma ciência oculta"? Isto é, sabes como fazer isso?

@IvoBastos Sinceramente não estou a ver como resolver essa questão...

**Comment by andredvasconcelos** [comment]
opa neste momento estou a ter dificuldades... nao consigo conectar a aplicação com o pc
Do que percebi, ao conectar a aplicação podemos criar varias coisas, uma delas uma joystick, e ela apenas envia mensagens para o cmd_vel... mas neste momento esta dificil

**Comment by bruno5198** [comment]
Boas malta!

@IvoBastos Como está esta parte do controlo de um robô com o recurso a um comando de PS3?
Apesar de o André já conseguir controlar um robô através do telemóvel, penso que acrescentaria valor ao trabalho conseguir também controlar um robô com um comando de PS3.

**Comment by IvoBastos** [comment]
Olá pessoal, infelizmente não consegui progredir mais na questão do controlo usando o comando PS3. Depois de não conseguir instalar os pacotes joy, vi na net que se podia instalar os pacotes de um comando xbox e que resultaria na mesma com o comando ps3. No entanto, depois tive um problema com o tipo de mensagens, porque o joystick enviava mensagens do tipo sensor msgs, e o cmd_vel requer geometry msgs. Não consegui fazer a transformação infelizmente.

**Comment by bruno5198** [comment]
@andredvasconcelos Não consegues dar uma ajuda numa tentativa de solucionar este problema?

**Comment by andredvasconcelos** [comment]
nao sei se consigo, vou tratar da parte do video da condução manual pela aplicação e depois tento dar uma olhadela
