### ISSUE TITLE
Ponto de situação!

### ISSUE THREAD

**Issue by bruno5198** [bruno5198/Trabalho3-Grupo1#9]
Boa tarde malta,

Só para que todos saibamos como está a evoluir o trabalho,
- @IvoBastos Como está a situação de controlar um robô através de um joystick (comando de PS3, por exemplo)?
- @andredvasconcelos Segundo sei, o controlo de um robô através do telemóvel ficou a funcionar, no entanto a camara não estava a dar...Conseguiste resolver essa parte? E já consegues fazer uma volta à pista em menis de 5 segundos? hehe
- Em relação ao @MartinRivadeneira é deixá-lo ir que o homem está imparável....Ainda à umas horas atualizou o código....Rumo ao 20

- Eu, estou a trabalhar na questão do planeamento do caminho para o rviz goal, isto é, já fiz com que os robôs conseguissem ir ao encontro de um goal definido por nós no rviz (dando o robô prioridade a isso), no entanto falta garantir que o mesmo se desvia de eventuais obstáculos que encontre pelo caminho.

**Comment by andredvasconcelos** [comment]
ainda nao consegui resolver esse problema... em relação ao controlo manual pela aplicação, substitui por minutos ahahahah

**Comment by bruno5198** [comment]
> ainda nao consegui resolver esse problema... em relação ao controlo manual pela aplicação, substitui por minutos ahahahah

O quê? 0.0833(3) minutos? hahaha
Tens que te tornar um condutor profissional de robôs até dia 3...

**Comment by bruno5198** [comment]
Boas malta!

Uma vez que a data de entrega deste trabalho se aproxima, penso que deveríamos começar a pensar em concluir as coisas, juntar o que houver para juntar e definir como iremos apresentar.
Eu e o @MartinRivadeneira já abordamos esta questão e falámos em juntarmo-nos amanhã. Vocês podem (@andredvasconcelos @IvoBastos)?

**Comment by andredvasconcelos** [comment]
Eu hoje nao consigo, soa partir de amanha

**Comment by bruno5198** [comment]
Da reunião de ontem resultou a seguinte lista de tarefas:
- Atualização das configurações do RViz associado a cada jogador (na versão p_bmendes) com vista à visualização do mapeamento da cena;
- Realização de um vídeo demonstrativo relativo à componente de condução manual de um robô;
- Realização de um vídeo demonstrativo relativo ao jogo TeamHunt.

Peço ao @MartinRivadeneira que adicione a esta mensagem, por favor, eventuais tarefas que me tenha esquecido de referir.

**Comment by bruno5198** [comment]
Dá-se por concluído o trabalho. Para mais detalhes sobre o mesmo clicar [aqui](https://github.com/bruno5198/Trabalho3-Grupo1/blob/main/README.md).
